### ISSUE TITLE
implement `std::error::Error` for `flagset::InvalidBits`

### ISSUE THREAD

**Issue by vxpm** [enarx/flagset#22]
right now, `flagset::InvalidBits`, the type returned within the `Err` variant when creating a new `flagset::FlagSet`, doesn't implement `std::error::Error`. not only is this unorthodox for error types, but it also makes it hard to propagate errors with flagset.

it would be nice to give `flagset::InvalidBits` a basic `std::error::Error` implementation.

**Comment by rjzak** [comment]
Done via https://github.com/enarx/flagset/commit/d5c80a74d06a0036ef89582c43f949ad29ce6bb2
