### ISSUE TITLE
Implement an automated test to detect merge commits

### ISSUE THREAD

**Issue by mbestavros** [enarx/flagset#7]
Enarx projects should not contain merge commits, and we'd like to test incoming pull requests to ensure they do not contain any.

The best way to go about this is probably to detect whether individual commits have multiple parents. There is no simple one-line way to do this, so we'll need to implement it from scratch (probably by iterating through PR commits and analyzing them).

**Comment by rjzak** [comment]
Unneeded, the repo settings only allow rebase merging, and branch protection rules for `main` require linear history.
